In [31]:
%load_ext autoreload
%autoreload 2
from src.config import RAW_DATA_PATH
from src.DataProcessor import explore_dataframe, extract_latest_values, add_prefix, create_trusted_order
from src.IOController import create_pyspark_session

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
spark = create_pyspark_session()

Starting PySpark session. Check your terminal for detailed logging...
PySpark session sucessfully created.

In [33]:
tmp = create_trusted_order(spark)

Starting processing to generate Order Items dataset...
Exporting dataset file system...
Dataset sucessfully exported to `/home/jovyan/data/trusted/order`!

In [34]:
type(spark)

pyspark.sql.session.SparkSession

In [ ]:
tmp.limit(3).toPandas().T

In [3]:
o_df = spark.read.parquet(str(RAW_DATA_PATH / 'order'))
explore_dataframe(o_df)
o_df.limit(3).toPandas().T

(#rows, #columns) = (3683040, 22)
root
 |-- cpf: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- delivery_address_city: string (nullable = true)
 |-- delivery_address_country: string (nullable = true)
 |-- delivery_address_district: string (nullable = true)
 |-- delivery_address_external_id: string (nullable = true)
 |-- delivery_address_latitude: string (nullable = true)
 |-- delivery_address_longitude: string (nullable = true)
 |-- delivery_address_state: string (nullable = true)
 |-- delivery_address_zip_code: string (nullable = true)
 |-- items: string (nullable = true)
 |-- merchant_id: string (nullable = true)
 |-- merchant_latitude: string (nullable = true)
 |-- merchant_longitude: string (nullable = true)
 |-- merchant_timezone: string (nullable = true)
 |-- order_created_at: timestamp (nullable = true)
 |-- order_id: string (nullable = true)
 |-- order_scheduled: boolean (nullable = true)
 |-- order_scheduled_date: timestamp (nullable = true)
 |-- order_total_amount: double (nullable = true)
 |-- origin_platform: string (nullable = true)

,0,1,2
cpf,80532101763,43352103961,38650991217
customer_id,977b9a89-825f-464b-8ef6-0f453d7334c1,e969cc0d-388b-4025-9351-0db0f718d81c,e08dcc8b-f998-405e-b3f2-7107ea8958cf
customer_name,GUSTAVO,MICHELLE,VICTOR
delivery_address_city,FRANCA,SANTOS,GUARULHOS
delivery_address_country,BR,BR,BR
delivery_address_district,JARDIM ESPRAIADO,CAMPO GRANDE,JARDIM ROSSI
delivery_address_external_id,6736655,8759216,8765930
delivery_address_latitude,-47.39,-46.34,-46.53
delivery_address_longitude,-20.55,-23.96,-23.44
delivery_address_state,SP,SP,SP
delivery_address_zip_code,14403,11070,71304
items,"[{""name"": ""Parmegiana de Filé de Frango (2 pes...","[{""name"": ""Filé Mignon à Cubana"", ""addition"": ...","[{""name"": ""GRANDE 2 SABORES"", ""addition"": {""va..."
merchant_id,eb4197f9-964c-4f87-8307-709e498aab87,927d46f9-4bb3-48f7-be1d-584deaf18adc,71ad62c5-5947-4518-9846-976fbdd2f881
merchant_latitude,-47.39,-46.34,-46.53
merchant_longitude,-20.55,-23.96,-23.44
merchant_timezone,America/Sao_Paulo,America/Sao_Paulo,America/Sao_Paulo
order_created_at,2019-01-17 22:50:06,2019-01-17 17:51:26,2019-01-17 22:53:47
order_id,dd4f8f0a-c2cb-45c6-a002-c3be6b305e5f,8dd80f0b-db00-4b88-b7e2-02ca706fc5a5,430f9887-a563-45ee-8001-1cb29597d9dd
order_scheduled,False,False,False
order_scheduled_date,NaT,NaT,NaT
order_total_amount,46,104.5,35
origin_platform,ANDROID,ANDROID,IOS

In [4]:
table = 'consumer'
c_df = spark.read.parquet(str(RAW_DATA_PATH / table))
explore_dataframe(c_df)
c_df = add_prefix(c_df, table)
c_df.limit(3).toPandas().T

(#rows, #columns) = (809323, 7)
root
 |-- customer_id: string (nullable = true)
 |-- language: string (nullable = true)
 |-- created_at: string (nullable = true)
 |-- active: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- customer_phone_area: string (nullable = true)
 |-- customer_phone_number: string (nullable = true)

,0,1,2
customer_id,00039466-560f-4e57-85a2-d4753cd901be,001a1267-31a3-4f5b-a028-d7e323864b08,003ae1d5-67b8-4a04-b055-0e4e9622771a
consumer_language,pt-br,pt-br,pt-br
consumer_created_at,2018-04-05T14:49:18.165Z,2018-01-14T21:40:02.141Z,2018-01-07T03:47:15.554Z
consumer_active,true,true,true
consumer_customer_name,NUNO,ADRIELLY,PAULA
consumer_customer_phone_area,46,59,62
consumer_customer_phone_number,816135924,231330577,347597883

In [5]:
table = 'restaurant'
r_df = spark.read.parquet(str(RAW_DATA_PATH / table))
explore_dataframe(r_df)
r_df = r_df.withColumnRenamed('id', 'merchant_id')
r_df = add_prefix(r_df, table)
r_df.limit(3).toPandas().T

(#rows, #columns) = (7292, 12)
root
 |-- id: string (nullable = true)
 |-- created_at: string (nullable = true)
 |-- enabled: string (nullable = true)
 |-- price_range: string (nullable = true)
 |-- average_ticket: string (nullable = true)
 |-- takeout_time: string (nullable = true)
 |-- delivery_time: string (nullable = true)
 |-- minimum_order_value: string (nullable = true)
 |-- merchant_zip_code: string (nullable = true)
 |-- merchant_city: string (nullable = true)
 |-- merchant_state: string (nullable = true)
 |-- merchant_country: string (nullable = true)

,0,1,2
merchant_id,02c94103-61f3-4906-a4a9-55611db9f28c,15e7f5fd-090d-47b9-9f14-b6f7fce3c95d,33ca5d3d-b99f-404d-84d9-8df8f38a2261
restaurant_created_at,2017-01-23T12:52:30.910Z,2017-01-20T13:14:48.286Z,2017-01-23T12:46:33.457Z
restaurant_enabled,false,true,true
restaurant_price_range,3,3,5
restaurant_average_ticket,60.0,60.0,100.0
restaurant_takeout_time,0,0,0
restaurant_delivery_time,50,0,45
restaurant_minimum_order_value,30.0,30.0,10.0
restaurant_merchant_zip_code,14025,50180,23090
restaurant_merchant_city,RIBEIRAO PRETO,SAO PAULO,RIO DE JANEIRO
restaurant_merchant_state,SP,SP,RJ
restaurant_merchant_country,BR,BR,BR

In [6]:
table = 'status'
s_df = spark.read.parquet(str(RAW_DATA_PATH / table))
explore_dataframe(s_df)
s_df = add_prefix(s_df, table)
s_df.limit(3).toPandas()

(#rows, #columns) = (11075048, 4)
root
 |-- created_at: timestamp (nullable = true)
 |-- order_id: string (nullable = true)
 |-- status_id: string (nullable = true)
 |-- value: string (nullable = true)

,status_created_at,order_id,status_id,status_value
0,2019-01-25 01:05:07,0002fe02-d7dc-4232-b7ac-3394019ce240,b4298862-fa38-499a-93e2-a76930fb2bce,CONCLUDED
1,2019-01-24 23:04:27,0002fe02-d7dc-4232-b7ac-3394019ce240,7964bf63-007a-484d-a321-e9118ccc2f97,REGISTERED
2,2019-01-24 23:04:28,0002fe02-d7dc-4232-b7ac-3394019ce240,ca16b92b-db8f-4274-b165-929675541a9f,PLACED

In [7]:
s_df = extract_latest_values(df=s_df, id_col='order_id', dt_col='status_created_at')
explore_dataframe(s_df)
s_df.limit(5).toPandas()

(#rows, #columns) = (2441067, 4)
root
 |-- status_created_at: timestamp (nullable = true)
 |-- order_id: string (nullable = true)
 |-- status_id: string (nullable = true)
 |-- status_value: string (nullable = true)

,status_created_at,order_id,status_id,status_value
0,2019-01-25 01:05:07,0002fe02-d7dc-4232-b7ac-3394019ce240,b4298862-fa38-499a-93e2-a76930fb2bce,CONCLUDED
1,2019-01-03 20:15:06,0012d95c-9c4b-4244-86b5-dcf87677dcc1,c8058ba4-1d1c-4a1f-8401-a7042ef6ba85,CONCLUDED
2,2019-01-06 16:20:27,0013fc5c-4c10-4402-886c-1b8166e4632e,d0a3ffd5-4e48-4cc4-9739-d5764678c19f,CONCLUDED
3,2019-01-03 15:55:12,00251da6-aa45-4512-be58-6622a248cdff,a621de13-5272-4c7c-969c-3bcd53f0515f,CONCLUDED
4,2019-01-21 22:20:02,00273652-efc8-4e7c-95b2-cd3827900e7e,74f8ff33-e731-477f-a698-4755577b80a1,CONCLUDED

In [8]:
s_df.groupBy('status_value').count().sort('count', ascending=False).show()

+------------+-------+
|status_value|  count|
+------------+-------+
|   CONCLUDED|2354218|
|   CANCELLED|  55179|
|      PLACED|  31654|
|  REGISTERED|     16|
+------------+-------+

In [9]:
tmp = (o_df
       .join(c_df, on='customer_id', how='left')
       .join(r_df, on='merchant_id', how='left')
       .join(s_df, on='order_id', how='left')
      )
tmp.limit(3).toPandas().T

,0,1,2
order_id,0002fe02-d7dc-4232-b7ac-3394019ce240,0012d95c-9c4b-4244-86b5-dcf87677dcc1,0012d95c-9c4b-4244-86b5-dcf87677dcc1
merchant_id,e3d24e4d-2f51-4987-8c39-47923b20b9be,e66b0dcc-ffa9-42ee-a864-60977672c3ef,e66b0dcc-ffa9-42ee-a864-60977672c3ef
customer_id,97c53c25-bd9b-41cb-8a0d-13cd74509f17,e2213649-cede-4770-b6e0-7ac1dd4d3548,e2213649-cede-4770-b6e0-7ac1dd4d3548
cpf,16854185492,05264105611,78163676650
customer_name,EDUARDO,BRUNO,BRUNO
delivery_address_city,SAO PAULO,SAO PAULO,SAO PAULO
delivery_address_country,BR,BR,BR
delivery_address_district,ITAIM BIBI,PENHA DE FRANCA,PENHA DE FRANCA
delivery_address_external_id,8847122,7632090,7632090
delivery_address_latitude,-46.68,-46.54,-46.54
delivery_address_longitude,-23.59,-23.52,-23.52
delivery_address_state,SP,SP,SP
delivery_address_zip_code,45381,36100,36100
items,"[{""name"": ""Pastel Frangolino"", ""addition"": {""v...","[{""name"": ""Porção Batata Frita"", ""addition"": {...","[{""name"": ""Porção Batata Frita"", ""addition"": {..."
merchant_latitude,-46.68,-46.54,-46.54
merchant_longitude,-23.59,-23.52,-23.52
merchant_timezone,America/Sao_Paulo,America/Sao_Paulo,America/Sao_Paulo
order_created_at,2019-01-24 23:04:27,2019-01-03 18:12:24,2018-12-04 18:12:24
order_scheduled,False,False,False
order_scheduled_date,NaT,NaT,NaT
order_total_amount,27,17.5,17.5
origin_platform,ANDROID,ANDROID,ANDROID
consumer_language,pt-br,pt-br,pt-br
consumer_created_at,2018-04-05T13:20:39.644Z,2018-01-06T14:31:43.348Z,2018-01-06T14:31:43.348Z
consumer_active,true,true,true
consumer_customer_name,EDUARDO,BRUNO,BRUNO
consumer_customer_phone_area,83,60,60
consumer_customer_phone_number,020082840,109441873,109441873
restaurant_created_at,2017-01-20T13:14:41.451Z,2017-01-20T13:14:16.179Z,2017-01-20T13:14:16.179Z
restaurant_enabled,true,true,true
restaurant_price_range,1,1,1
restaurant_average_ticket,30.0,30.0,30.0
restaurant_takeout_time,0,20,20
restaurant_delivery_time,40,0,0
restaurant_minimum_order_value,30.0,0.0,0.0
restaurant_merchant_zip_code,56560,36350,36350
restaurant_merchant_city,SAO PAULO,SAO PAULO,SAO PAULO
restaurant_merchant_state,SP,SP,SP
restaurant_merchant_country,BR,BR,BR
status_created_at,2019-01-25 01:05:07,2019-01-03 20:15:06,2019-01-03 20:15:06
status_id,b4298862-fa38-499a-93e2-a76930fb2bce,c8058ba4-1d1c-4a1f-8401-a7042ef6ba85,c8058ba4-1d1c-4a1f-8401-a7042ef6ba85
status_value,CONCLUDED,CONCLUDED,CONCLUDED

Fix schema and anonymize sensitive data

In [11]:
# for dtype, cols in dtypes.items():
#     for col in cols:
#         df = df.withColumn(col, df[col].cast(dtype))